name: casing
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.22
  - scipy>=1.12
  - pymatsolver>=0.3
  - matplotlib
  - discretize>=0.11
  - geoana>=0.7
  - scooby
  - empymod>=2.0.0
  - jupyter

# solver
# uncomment the next line if you are on an intel platform
  - pydiso # if on intel pc
# uncomment this line if you want to install mumps solvers
#  - python-mumps